export const OperatorsArr = [
  { id: 0, operator: 'C' },
  { id: 1, operator: '7' },
  { id: 2, operator: '8' },
  { id: 3, operator: '9' },
  { id: 4, operator: '*' },
  { id: 5, operator: '-' },
  { id: 6, operator: '4' },
  { id: 7, operator: '5' },
  { id: 8, operator: '6' },
  { id: 9, operator: '/' },
  { id: 10, operator: '+' },
  { id: 11, operator: '1' },
  { id: 12, operator: '2' },
  { id: 13, operator: '3' },
  { id: 14, operator: '=' },
  { id: 15, operator: '.' },
  { id: 16, operator: '(' },
  { id: 17, operator: '0' },
  { id: 18, operator: ')' },
  { id: 19, operator: 'CE' },
  { id: 20, operator: '%' },
  { id: 21, operator: '+/-' },
  { id: 22, operator: '' },
  { id: 23, operator: '' },
  { id: 24, operator: '' },
];
