export const props = {
  BTN_WIDTH: '50',
  BTN_HEIGHT: '50',
  BTN_BORDER_R: '12',
  BORDER_WIDTH: '1',
  FS_BIG: '30',
  DISPLAY_W: '80',
  BG_GRAY: 'gray',
  HEADER_PADDING: '10',
  FS_NORMAL: '18',
  BG_BLACK: 'black',
  MR_5: '5',
  M_10: '10',
  FS_SMALL: '16',
  P_8: '8',
  LINE_HEI_24: '24',
  SELECT_H: '40',
  SELECT_W: '40',
  BIG_BTN_W: '250',
};
